version: '3'
services:
  python:
    hostname: local-python
    image: local-python
    container_name: local-python
    build:
      context: ./
      dockerfile: ./containers/python/Dockerfile
    environment:
      POSTGRES_PORT: '5432'
      POSTGRES_USERNAME: 'pipeline'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DATABASE: 'sales_db'
      PUBSUB_TOPIC: 'ecom_topic'
    volumes:
      - ./source/scripts:/usr/src/app
    stdin_open: true
