version: '3'
services:
  python:
    hostname: local-python
    image: local-python
    container_name: local-python
    build:
      context: ./
      dockerfile: ./containers/python/Dockerfile
    environment:
      POSTGRES_PORT: '5432'
      POSTGRES_USERNAME: 'pipeline'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DATABASE: 'sales_db'
      PUBSUB_TOPIC: 'ecom_topic'
      PUBSUB_PROJECT: 'playground-s-11-6ef63277'
      GOOGLE_APPLICATION_CREDENTIALS: './scripts/keys/key.json'
    volumes:
      - ./source/scripts:/usr/src/app
    stdin_open: true
